//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aw_lab_liec
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_mrp_concreto
    {
        public System.Guid id_mrp_concreto { get; set; }
        public int id_est_concreto { get; set; }
        public string no_muesra { get; set; }
        public Nullable<System.DateTime> fecha_colado { get; set; }
        public Nullable<System.DateTime> fecha_recibe { get; set; }
        public string entrega { get; set; }
        public string recibe { get; set; }
        public Nullable<int> presion { get; set; }
        public int id_tipo_especimen { get; set; }
        public int id_tipo_concreto { get; set; }
        public int id_sit_concreto { get; set; }
        public Nullable<System.DateTime> C24_horas { get; set; }
        public Nullable<System.DateTime> C3_dias { get; set; }
        public Nullable<System.DateTime> C7_dias { get; set; }
        public Nullable<System.DateTime> C14_dias { get; set; }
        public Nullable<System.DateTime> C28_dias { get; set; }
        public Nullable<int> otra { get; set; }
        public System.Guid id_usuario { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public System.Guid id_emp { get; set; }
    
        public virtual fac_sit_concreto fac_sit_concreto { get; set; }
        public virtual fac_tipo_concreto fac_tipo_concreto { get; set; }
        public virtual fact_especimen fact_especimen { get; set; }
        public virtual fact_est_concreto fact_est_concreto { get; set; }
        public virtual inf_emp inf_emp { get; set; }
    }
}
